import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';

const initialState = {
	address: "",
	props: {
		center: [
			54.3109694,
			48.3712797
		],
		zoom: 14
	}
};


export const mapSlice = createSlice({
	name: 'map',
	initialState,
	reducers: {
		setAddress(state, action) {
			state.address = action.payload
		},
		removeAddress() { }
	},
	// The `extraReducers` field lets the slice handle actions defined elsewhere,
	// including actions generated by createAsyncThunk or in other slices.


});

export const { setAddress, removeAddress } = mapSlice.actions;


export default mapSlice.reducer;
